// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Pvyu5zSNLpH4X1XNT2Tl6kNaiyJUB0w',
    appId: '1:983017452505:web:1649b16163b5d5e8a89fc8',
    messagingSenderId: '983017452505',
    projectId: 'intromobileprojectfb',
    authDomain: 'intromobileprojectfb.firebaseapp.com',
    storageBucket: 'intromobileprojectfb.appspot.com',
    measurementId: 'G-F9VJYGS1B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD41TX8k2Z5p1hEvXGlALabZFmNAjRf_Pw',
    appId: '1:983017452505:android:3adb04617153aac0a89fc8',
    messagingSenderId: '983017452505',
    projectId: 'intromobileprojectfb',
    storageBucket: 'intromobileprojectfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxoiVfF0JQE1752nogebncsPq-IKollFA',
    appId: '1:983017452505:ios:a74513f45b9fc044a89fc8',
    messagingSenderId: '983017452505',
    projectId: 'intromobileprojectfb',
    storageBucket: 'intromobileprojectfb.appspot.com',
    iosBundleId: 'com.example.intormobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxoiVfF0JQE1752nogebncsPq-IKollFA',
    appId: '1:983017452505:ios:a74513f45b9fc044a89fc8',
    messagingSenderId: '983017452505',
    projectId: 'intromobileprojectfb',
    storageBucket: 'intromobileprojectfb.appspot.com',
    iosBundleId: 'com.example.intormobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Pvyu5zSNLpH4X1XNT2Tl6kNaiyJUB0w',
    appId: '1:983017452505:web:f78cceb345d67cb4a89fc8',
    messagingSenderId: '983017452505',
    projectId: 'intromobileprojectfb',
    authDomain: 'intromobileprojectfb.firebaseapp.com',
    storageBucket: 'intromobileprojectfb.appspot.com',
    measurementId: 'G-B6CFV81R5W',
  );
}
